# [external]
# cgi-dir = ["/usr/lib/chawan/cgi-bin/"]

[buffer]
images = true
cookie = true
autofocus = true
# scripting = true

[page]
' r' = "pager.externFilterSource('rdrview -H -u \"$CHA_URL\"')"
' f' = "pager.externFilterSource('fmt')"
