swipe:
  3:
    # right:
    #   sendkey: 'LEFTALT+LEFT' # History back
    # left:
    #   sendkey: 'LEFTALT+RIGHT' # History forward
    up:
      command: "ydotool key 29:1 20:1 20:0 29:0"  # ctrl+t
      # keypress:
      #   LEFTSHIFT:
      #     command: "ydotool key 29:1 42:1 20:1 20:0 42:0 29:0"  # ctrl+shift+t
    down:
      command: "ydotool key 29:1 17:1 17:0 29:0"  # ctrl+w
  # 4:
  #   left:
  #     command: "ydotool key 125:1 47:1 47:0 125:0" # right desktop super+v
      # keypress:
      #   LEFTSHIFT: 
      #     window: 'next' # Move window to next workspace
        # LEFTMETA:
        #   command: 'xdotool key --clearmodifiers super+ctrl+Right' # Move window to left side
    # right:
    #   command: "ydotool key 125:1 46:1 46:0 125:0" # right desktop super+c
      # keypress:
      #   LEFTSHIFT: 
      #     window: 'prev' # Move window to previous workspace
        # LEFTMETA:
        #   command: 'xdotool key --clearmodifiers super+ctrl+Right'  # Move window to right side
  #   up:
  #     command: 'xdotool key Control_L+F10' # Workspace overview
  #     keypress:
  #       LEFTMETA:
  #         window:
  #           maximized: 'toggle' # Toggle Maximize/Unmaximize Window
  #   down:
  #     command: 'xdotool key Control_L+F12' #minimise all windows
  #     keypress:
  #       LEFTMETA:
  #         window: 'close' # Close window

# pinch:
#   2:
#     in:
#       command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
#     out:
#       command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out
#   4:
#     in:
#       command: 'xdotool key Control_L+F8' # Desktop overview
#     # out:
#     #   command: 'xdotool key super+s' # Workspace overview

# plugin: 
#   inputs:
#     libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
#       enable-tap: true # click to tap
#       enable-dwt: true # disable tap while typing
#       show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option

threshold:
  pinch: 0.3

interval:
  pinch: 0.3
