[[mgr.prepend_keymap]]
on = ["<C-n>"]
run = '''
	shell 'dragon-drop -a -x "$@"'
'''

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["R"]
run = '''
    shell "$@" --block
'''
desc = "Execute the scripts"

[[mgr.prepend_keymap]]
on = ["J"]
run = "arrow 5"

[[mgr.prepend_keymap]]
on = ["K"]
run = "arrow -5"

[[mgr.prepend_keymap]]
on = ["<A-j>"]
run = "seek 5"

[[mgr.prepend_keymap]]
on = ["<A-k>"]
run = "seek -5"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"
