#!/usr/bin/env bash

file=$1

# MIME=$(mimetype --all --brief "$1")
MIME=$(file -Lb --mime-type "$file")

case "$MIME" in
    # images
    *image/*)
        w=$2
        h=$3
        x=$4
        y=$5
        kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
        exit 1
        ;;
    # video & audio
    *video/* | *audio/*)
        exiftool "$1" || mediainfo "$1"
        ;;
    # .pdf
    *application/pdf*)
        pdftotext "$1" -
        ;;
    # .7z
    *application/x-7z-compressed*)
        7z l "$1"
        ;;
    *application/gzip*)
        gzip -l "$1"
        ;;
    # .tar .tar.Z
    *application/x-tar*)
        tar -tvf "$1"
        ;;
    # .tar.*
    *application/x-compressed-tar*|*application/x-*-compressed-tar*)
        tar -tvf "$1"
        ;;
    # .rar
    *application/vnd.rar*)
        unrar l "$1"
        ;;
    # .zip
    *application/zip*)
        unzip -l "$1"
        ;;
    # any plain text file that doesn't have a specific handler
    *text/* | *application/javascript* | *application/json*)
        # return false to always repaint, in case terminal size changes
        bat --force-colorization --paging=never --style=changes \
            --terminal-width $(($2 - 3)) "$1" && false
        ;;
    *)
        echo "unknown format: $MIME"
        ;;
esac
# pistol "$file"
